"""Maze Runner 2D, by Al Sweigart al@inventwithpython.com
Move around a maze and try to escape. Maze files are generated by
mazemakerrec.py.
This code is available at https://nostarch.com/big-book-small-python-programming
Tags: large, game, maze"""

import sys, os
from tkinter import Tk, Canvas, filedialog, DISABLED, PhotoImage, Button, Label, messagebox, Toplevel

# Maze file constants:
WALL = '#'
EMPTY = ' '
START = 'S'
EXIT = 'E'

PLAYER = '@'  # (!) Try changing this to '+' or 'o'.
BLOCK = chr(9617)  # Character 9617 is '░'


def displayMaze(maze):
    c.delete('all')
    # Display the maze:
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if (x, y) == (playerx, playery):
                c.create_image(x*20, y*20, image=avatar, tags='all', anchor='nw')
            elif (x, y) == (exitx, exity):
                c.create_image(x*20, y*20, image=end, tags='all', anchor='nw')
            elif maze[(x, y)] == WALL:
                c.create_image(x*20, y*20, image=wall, tags='all', anchor='nw')

def start():
    root.withdraw()
    global win
    for i in ctrlbuttons:
        i['command'] = DISABLED
    for i in [('Left', 'A'), ('Up', 'W'), ('Right', 'D'), ('Down', 'S')]:
        root.unbind(f'<{i[0]}>')
    win = Toplevel(root)
    win.title('Maze Runner 3D')
    Label(win, text='Welcome to Maze Runner 2D!\nUse the up, down, left, and right keys or arrow keys to\nmove your character around the maze and reach the exit.\nClick Start to start!').pack()
    Button(win, text='Start', command=get_file).pack()

def get_file():
    global WIDTH, HEIGHT
    try:
        win.destroy()
    except:
        pass
    global maze, playerx, playery, exitx, exity, pDir, avatarwin
    filename = filedialog.askopenfilename(title='Select maze file', filetypes=(("Text files", "*.txt"),))
    if filename == '':
        start()
        return
    # Load the maze from a file:
    mazeFile = open(filename)
    maze = {}
    lines = mazeFile.readlines()
    mazeFile.close()
    px = None
    py = None
    exitx = None
    exity = None
    y = 0
    brk = False
    for line in lines:
        WIDTH = len(line.rstrip())
        for x, character in enumerate(line.rstrip()):
            if not character in (WALL, EMPTY, START, EXIT, '\n'): 
                messagebox.showwarning(message='Invalid character at column {}, line {}'.format(x + 1, y + 1))
                get_file()
            if character in (WALL, EMPTY):
                maze[(x, y)] = character
            elif character == START:
                playerx, playery = x, y
                maze[(x, y)] = EMPTY
            elif character == EXIT:
                exitx, exity = x, y
                maze[(x, y)] = EMPTY
        y += 1
    HEIGHT = y

    if not playerx != None and playery != None:
        messagebox.showwarning(message='No start point in file.')
        get_file()
    if not exitx != None and exity != None:
        messagebox.showwarning(message='No exit point in file.')
        get_file()
    avatarwin = Toplevel(root)
    avatarwin.title('Select avatar')
    avatarwin.protocol('WM_DELETE_WINDOW', sys.exit)
    Label(avatarwin, text='Select an avatar:').grid(column=0, row=0, columnspan=2)
    Button(avatarwin, image=boy2, command=lambda: start_maze(boy)).grid(column=0, row=1)
    Button(avatarwin, image=girl2, command=lambda: start_maze(girl)).grid(column=1, row=1)

def start_maze(a):
    global avatar
    avatar = a
    avatarwin.destroy()
    motions = {0:'A', 3:'W', 2:'D', 1:'S'}
    root.deiconify()
    c.config(width=WIDTH*20, height=HEIGHT*20)
    displayMaze(maze)
    ctrlbuttons[0]['command'] = lambda: move(motions[0])
    ctrlbuttons[1]['command'] = lambda: move(motions[1])
    ctrlbuttons[2]['command'] = lambda: move(motions[2])
    ctrlbuttons[3]['command'] = lambda: move(motions[3])
    root.bind(f'<Left>', lambda e: move(motions[0]))
    root.bind(f'<Right>', lambda e: move(motions[2]))
    root.bind(f'<Up>', lambda e: move(motions[3]))
    root.bind(f'<Down>', lambda e: move(motions[1]))

def move(dir):
    global playerx, playery
    if dir == 'W' and maze[(playerx, playery - 1)] == EMPTY:
        while True:
            playery -= 1
            if (playerx, playery) == (exitx, exity):
                break
            if maze[(playerx, playery - 1)] == WALL:
                break  # Break if we've hit a wall.
            if (maze[(playerx - 1, playery)] == EMPTY
                or maze[(playerx + 1, playery)] == EMPTY):
                break  # Break if we've reached a branch point.
    elif dir == 'S' and maze[(playerx, playery + 1)] == EMPTY:
        while True:
            playery += 1
            if (playerx, playery) == (exitx, exity):
                break
            if maze[(playerx, playery + 1)] == WALL:
                break  # Break if we've hit a wall.
            if (maze[(playerx - 1, playery)] == EMPTY
                or maze[(playerx + 1, playery)] == EMPTY):
                break  # Break if we've reached a branch point.
    elif dir == 'A' and maze[(playerx - 1, playery)] == EMPTY:
        while True:
            playerx -= 1
            if (playerx, playery) == (exitx, exity):
                break
            if maze[(playerx - 1, playery)] == WALL:
                break  # Break if we've hit a wall.
            if (maze[(playerx, playery - 1)] == EMPTY
                or maze[(playerx, playery + 1)] == EMPTY):
                break  # Break if we've reached a branch point.
    elif dir == 'D' and maze[(playerx + 1, playery)] == EMPTY:
        while True:
            playerx += 1
            if (playerx, playery) == (exitx, exity):
                break
            if maze[(playerx + 1, playery)] == WALL:
                break  # Break if we've hit a wall.
            if (maze[(playerx, playery - 1)] == EMPTY
                or maze[(playerx, playery + 1)] == EMPTY):
                break  # Break if we've reached a branch point.
    displayMaze(maze)
    if (playerx, playery) == (exitx, exity):
        for i in ctrlbuttons:
            i['command'] = DISABLED
        for i in [('Left', 'A'), ('Up', 'W'), ('Right', 'D'), ('Down', 'S')]:
            root.unbind(f'<{i[0]}>')
        displayMaze(maze)
        c.create_text(10, 10, text='You have reached the exit!\nGood job!', tags='all', anchor='nw')
        c.create_text(10, 60, text='You can play again by\npressing Restart.', tags='all', anchor='nw')

def help():
    win2 = Toplevel(root)
    Label(win2, text='Welcome to Maze Runner 3D!\nUse the up, down, left, and right keys or arrow keys to\n\
move your character around the maze and reach the exit. (marked by the 🔚 arrow)\n\
You can use this program to explore mazes you create in a text editor.\n\
When creating your maze, use # for walls, a space for empty areas,\n\
an S for a start and an X for an exit. You must save your mazes as\n\
a .txt (text) file.\n\
At any time during the game, press Restart to choose a new maze.').pack()
    Button(win2, text='Back', command=win2.destroy).pack()

root = Tk()
boy = PhotoImage(file='boy.png')
boy2 = PhotoImage(file='boy2.png')
girl = PhotoImage(file='girl.png')
girl2 = PhotoImage(file='girl2.png')
end = PhotoImage(file='end.png')
wall = PhotoImage(file='wall.png')
root.title('Maze Runner 2D')
c = Canvas(root, width=340, height=440)
c.grid(column=0, row=0, columnspan=3)
ctrlbuttons = []
for i, j in enumerate(('←', '↓', '→')):
    b=Button(root, width=3, height=3, text=j, command=DISABLED)
    b.grid(column=i, row=2)
    ctrlbuttons.append(b)
b = Button(root, width=3, height=3, text='↑', command=DISABLED)
b.grid(column=1, row=1)
ctrlbuttons.append(b)
Button(root, text='Restart', command=start).grid(column=0, row=3, columnspan=3)
Button(root, text='Help', command=help).grid(column=0, row=4, columnspan=3)

root.withdraw()
start()
root.mainloop()